GET http://localhost:8000/client/user/page/structure.list
Content-Type: application/json
Accept: application/json

{
    "size":10
}

###

POST http://localhost:8000/client/user/get
Content-Type: application/json
Accept: application/json

{
  "name":"张三"
}


###